### ISSUE TITLE
Inconsistent indents in .gitconfig file

### ISSUE THREAD

**Issue by pwittchen** [adambro/dotfiles#1]
Hi Adam,

There are inconsistent indents in `.gitconfig` file in the following lines:
- https://github.com/adambro/dotfiles/blob/master/home/.gitconfig#L31
- https://github.com/adambro/dotfiles/blob/master/home/.gitconfig#L32
- https://github.com/adambro/dotfiles/blob/master/home/.gitconfig#L47

Regards,
Piotr
(-:

**Comment by adambro** [comment]
Thanks for pointing this out. I fixed them all. Feel free to use it at will :)

Cheers, Adam
